% GENERATEOSIMAGERY.M
% generateOsImagery()
% -------------------------------------------------------------------------
% DESCRIPTION: Takes screenshots of images generated by the OS and saves
% them to the current directory
% -------------------------------------------------------------------------
% REFERENCES:
% -------------------------------------------------------------------------
% AUTHOR: Sumant Sharma
%         2018-03-20 SS: Created
% -------------------------------------------------------------------------
% COPYRIGHT: 2018 SLAB Group
% -------------------------------------------------------------------------

clc
clearvars -EXCEPT results
close all

%% Controls
saveImages = 1;
saveMasks = 0;

%% Configurations
if ~exist('results','var')
    tronImageDir = fullfile('D:','GAN','pix2pix','images','TangoGanExp04','rawReal50');
    load(fullfile(tronImageDir, 'exp1_results.mat'));
end

%% Determine relative attitude and position using vicon data
q_vbs2tango = zeros(length(results),4);
r_Vo2To_vbs = zeros(length(results),3);
% R_tango2gl =  Rz(-20*pi/180)*Ry(-40*pi/180)*Rx(-60*pi/180)*[-1 0 0;0 -1 0; 0 0 1];
R_tango2gl =  eye(3);

for i = 1:length(results)
    R_vicon2vbs = results{i}.camState.R_vicon2object;
    R_vicon2tango = results{i}.tangoState.R_vicon2object;
    R_vbs2tango = R_tango2gl* R_vicon2tango * R_vicon2vbs';
    q_vbs2tango(i,:) = os_rotation2quaternion(R_vbs2tango)';
    
    r_vicon2vbs = results{i}.camState.r_vicon_meters;
    r_vicon2tango = results{i}.tangoState.r_vicon_meters;
    r_Vo2To_vbs(i,:) = 0.5 * eye(3,3) * R_vicon2vbs * (r_vicon2tango - r_vicon2vbs);
end


%% Take screenshots of images
if saveImages
    os = OpticalStimulator(1920, 1200, 5.86e-6, 5.8e-6, 0.022, 0.022);
    imageDir = fullfile('D:', 'GAN', 'pix2pix', 'images', 'TangoGanExp05', 'syn50');
    os.GAN(1,r_Vo2To_vbs,q_vbs2tango, imageDir)
    os.terminate
    
    files = dir(fullfile('D:', 'GAN', 'pix2pix', 'images', 'TangoGanExp05', 'syn50','*.jpg'));
    for i = 1:length(files)
        im = imread(fullfile(files(i).folder, files(i).name));
        im = flipud(im);
        imwrite(im,fullfile(files(i).folder, files(i).name));
    end
    
end

%% Take screenshots of image masks
if saveMasks
    imageMaskDir = fullfile('D:', 'GAN', 'pix2pix', 'images', 'TangoGanExp04', 'syn50', 'imageMasks');
    os = OpticalStimulator(1920, 1200, 5.86e-6, 5.8e-6, 0.017, 0.017);
    os.Ghost(r_Vo2To_vbs, q_vbs2tango, imageMaskDir)
    os.terminate
end


